<a href="https://colab.research.google.com/github/malkang92/deep-learning-from-scratch/blob/exercise/5_%EC%98%A4%EC%B0%A8%EC%97%AD%EC%A0%84%EB%B2%95_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
class MulLayer:
  def __init__(self):
    self.x = None
    self.y = None
    
  def forward(self, x, y):
    self.x = x
    self.y = y
    out = x*y
    
    return out
  
  def backward(self, dout):
    dx = dout * self.y #x와y를 바꾼다
    dy = dout * self.x
    
    return dx, dy

In [0]:
apple = 100
apple_num = 2
tax = 1.1

mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

apple_price = mul_apple_layer.forward(apple, apple_num)
price = mul_tax_layer.forward(apple_price, tax)

print(price)

220.00000000000003


In [0]:
dprice = 1
dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(dapple, dapple_num, dtax)

2.2 110.00000000000001 200


In [0]:
class AddLayer:
  def __init__(self):
    pass
  
  def forward(self, x, y):
    out = x+y
    return out
  
  def backward(self, dout):
    dx = dout *1
    dy = dout*1
    return dx, dy

In [0]:
apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax =1.1

mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_tax_layer = MulLayer()

apple_price = mul_apple_layer.forward(apple, apple_num)
orange_price = mul_orange_layer.forward(orange, orange_num)
all_price = add_apple_orange_layer.forward(apple_price, orange_price)
price = mul_tax_layer.forward(all_price, tax)

dprice = 1
dall_price, dtax = mul_tax_layer.backward(dprice)

dapple_price, dorange_price = add_apple_orange_layer.backward(dall_price)
dorange, dorange_num = mul_orange_layer.backward(dorange_price)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(price)
print(dapple_num, dapple, dorange, dorange_num, dtax)

715.0000000000001
110.00000000000001 2.2 3.3000000000000003 165.0 650


In [0]:
class Relu:
  def __init__(self):
    self.mask=None
    
  def forward(self, x):
    self.mask = (x<= 0)
    out = x.copy()
    out[self.mask]=0
    
  def backward(self, dout):
    dout[self.mask] = 0
    dx = dout
    
    return dx

In [0]:
x = np.array([[1.0,-0.5], [-2.0, 3.0]])
print(x)

[[ 1.  -0.5]
 [-2.   3. ]]


In [0]:
mask = (x<=0)
print(mask)

[[False  True]
 [ True False]]


In [0]:
class  Siggmoid: 
  def __init__(self):
    self.out = None

def forward(self, x):
  out = 1/(1+np.exp(-1))
  self.out = out

  def backward(self, dout):
    dx = dout * (1.0-self.out)*self.out

    return dx
  

## 5.6 Affine/Softmax 계층 구현

### 5.6.1 Affine 계층

In [14]:
x = np.random.rand(2)
w = np.random.rand(2,3)
b = np.random.rand(3)

print(x.shape)
print(w.shape)
print(b.shape)

(2,)
(2, 3)
(3,)


In [0]:
y = np.dot(x,w)+b

In [16]:
print(x)

[0.93862173 0.0956627 ]


In [17]:
print(w)

[[0.12012357 0.89370191 0.84376208]
 [0.17373535 0.49211069 0.91415221]]


In [18]:
print(b)

[0.40243169 0.06370758 0.04905398]


In [20]:
print(y)

[0.53180228 0.94963226 0.92847768]


In [21]:
print(y.shape)

(3,)


In [0]:
ax = np.array([[2.0],[3.0]])

In [27]:
print(ax.shape)

(2, 1)


### 5.6.2. 배치용 Affine 계층

In [29]:
x = np.random.rand(4,2)
w = np.random.rand(2,3)
b = np.random.rand(3)

print(x)


[[0.53890831 0.84832894]
 [0.7025963  0.73554455]
 [0.0351285  0.1117962 ]
 [0.15038589 0.53494688]]


In [32]:
print(w)

[[0.89776614 0.35053114 0.51010838]
 [0.78126899 0.46749037 0.25006325]]


In [31]:
print(b)

[0.64491963 0.71064057 0.5619141 ]


In [33]:
y = np.dot(x,w)+b
print(y)

[[1.79150635 1.29613032 1.04895163]
 [1.85034494 1.30078244 1.10424702]
 [0.76379971 0.77521785 0.60778956]
 [1.1978684  1.01343802 0.77239775]]


In [38]:
0.53890831*0.35053114 + 0.84832894*0.46749037+0.71064057

1.2961303243020812

In [44]:
x_dot_w = np.array([[0,0,0],[10,10,10]])
print(x_dot_w.shape)

(2, 3)


In [0]:
b=np.array([1,2,3])

In [45]:
x_dot_w

array([[ 0,  0,  0],
       [10, 10, 10]])

In [46]:
x_dot_w +b

array([[ 1,  2,  3],
       [11, 12, 13]])

In [48]:
dy = np.array([[1,2,3],[4,5,6]])
dy

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
db = np.sum(dy, axis = 0)
db

array([5, 7, 9])

In [0]:
class Affine:
  def __init__(self, w,b):
    self.w = w
    self.b = b
    self.x = None
    self.dw = None
    self.db = None

  def forward(self,x):
    self.x = x
    out = np.dot(x, self.w) + self.b

    return out

    def backward(self, dout):
      dx = np.dot(dout, self.w.t)
      self.dw = np.dot(self.x.t, dout)
      self.db = np.sum(dout, axis=0)

      return dx

### 5.6.3 Softmax-with-Loss 계층
* 소프트맥스 계층은 입력 값을 정규화(출력의 합이 1이 되도록 변형)
* 추론을 할 때는 소프트맥스 계층을 일반적으로 사용하지 않음
* 신경망 추론에서 답을 하나만 내는 경우에는 가장 높은 점수만 알려되므로 소프트맥스 계층을 통한 정규화 필요 없음

In [0]:
class SoftmaxWithLoss:
  def __init__(self):
    self.loss = None
    self.y = None
    self.t = None

  def forward(self, x, t):
    self.t = t
    self.y = softmax(x)
    self.loss = cross_entropy_error(self.y, self.t)
    return self.loss

  def backward(self, dout =1):
    batch_size = self.t.shape[0]
    dx = (self.y-self.t) / batch_size

    return dx